### ISSUE TITLE
歌单获取错误

### ISSUE THREAD

**Issue by lovecn** [messoer/Music-Downloader#5]
刚下载的软件，地址是https://github.com/messoer/Music-Downloader/releases/download/1.4.2/MusicDownloader.zip 
![image.png](https://upload-images.jianshu.io/upload_images/17817191-bbd6a7a2a6fcb58c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by NiTian1207** [comment]
![TIM截图20190825004011](https://user-images.githubusercontent.com/40469236/63640308-1be57d80-c6d1-11e9-901d-878301db7d39.png)
